version: '3.8'
services:

  #
  # OAuth and API calls from the SPA are routed via the gateway at the https://api.mycompany.com:444 base URL
  #
  apigateway:
    image: kong:2.5.0-alpine
    hostname: apigateway-internal.mycompany.com
    extra_hosts:
     - api.mycompany.com:host-gateway
    ports:
      - 444:8000
    volumes:
      - ./apigateway/kong.yml:/usr/local/kong/declarative/kong.yml
      - ./oauth-proxy-plugin/plugin/plugin.lua:/usr/local/share/lua/5.1/kong/plugins/oauth-proxy/access.lua
      - ./oauth-proxy-plugin/plugin/handler.lua:/usr/local/share/lua/5.1/kong/plugins/oauth-proxy/handler.lua
      - ./oauth-proxy-plugin/plugin/schema.lua:/usr/local/share/lua/5.1/kong/plugins/oauth-proxy/schema.lua
      - ./oauth-proxy-plugin/plugin/kong-oauth-proxy-1.0.0-1.rockspec:/usr/local/share/lua/5.1/kong/plugins/oauth-proxy/oauth-proxy-1.0.0-1.rockspec
      - ./certs/mycompany.ssl.pem:/usr/local/share/certs/mycompany.ssl.pem
      - ./certs/mycompany.ssl.key:/usr/local/share/certs/mycompany.ssl.key
      - ./certs/mycompany.ca.pem:/usr/local/share/certs/mycompany.ca.pem
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/usr/local/kong/declarative/kong.yml'
      KONG_PROXY_LISTEN: '0.0.0.0:8000 ssl'
      KONG_SSL_CERT: '/usr/local/share/certs/mycompany.ssl.pem'
      KONG_SSL_CERT_KEY: './usr/local/share/certs/mycompany.ssl.key'
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: './usr/local/share/certs/mycompany.ca.pem'
      KONG_LOG_LEVEL: 'info'
      KONG_PLUGINS: 'bundled,oauth-proxy'
      KONG_NGINX_PROXY_PROXY_BUFFERS: '16 64k'
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: '64k'
      KONG_NGINX_PROXY_LARGE_CLIENT_HEADER_BUFFERS: '16 64k'

  #
  # OAuth calls and issuing of secure cookies for the SPA are handled by this utility API
  #
  tokenhandlerapi:
    image: tokenhandler:v1
    hostname: api-internal.mycompany.com
    volumes:
      - ./tokenhandlerapiconfig/api.config.json:/usr/api/api.config.json
      - ./certs/mycompany.ssl.p12:/usr/api/certs/mycompany.ssl.p12
